/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package terminplaner;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KrempLen
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Termin set = null;
    TerminPlaner t;

    public GUI(TerminPlaner t) {
        initComponents();
        this.t = t;
    }

    public void fillDisplay() {
        //fills display with 3 nearest events
        Termin[] show = new Termin[3];
        //checks if there are events
        if (t.getNext().length != 0) {
            //checks if there are more than 3 events
            if (t.getNext().length >= 3) {
                for (int i = 0; i < 3; i++) {
                    show[i] = t.getNext()[i];
                }
            } else {
                //if there are 2 or less events:
               // System.out.println(t.getNext().length);
                //get Termin array from terminplaner
                Termin[] fe = new Termin[t.getNext().length];
                fe = t.getNext();
                for (int i = 0; i < t.getNext().length; i++) {
                    // System.out.println(i);  
                    //copy termine to other array
                    show[i] = fe[i];
                    // System.out.println(""+fe[0]);
                }
            }
            //display termine in textarea
            if (t.getNext().length == 1) {

                display.setText("1. " + show[0].getDescription() + " von " + show[0].getSTime() + " bis " + show[0].getETime()+"\n Anzahl der Termine Insgesamt "+t.getNext().length);
            } else if (t.getNext().length == 2) {

                display.setText("1. " + show[0].getDescription() + " von " + show[0].getSTime() + " bis " + show[0].getETime() + "\n 2." + show[1].getDescription() + " von " + show[1].getSTime() + " bis " + show[1].getETime()+" \n Anzahl der Termine Insgesamt "+t.getNext().length);
            } else {
                display.setText("1. " + show[0].getDescription() + " von " + show[0].getSTime() + " bis " + show[0].getETime() + "\n 2." + show[1].getDescription() + " von " + show[1].getSTime() + " bis " + show[1].getETime() + "\n 3." + show[2].getDescription() + " von " + show[2].getSTime() + " bis " + show[2].getETime()+" \nAnzahl der Termine Insgesamt "+t.getNext().length);
            }
        }
    }

    public void getAttributes() {
        String descriptions = description.getText();
        int times = Integer.parseInt(time.getText());
        int ends = Integer.parseInt(end.getText());
        t.add(descriptions, times, ends);

    }

    public void suchen(int search) throws InterruptedException {
     
        set = null;
        for (Termin x : t.getNext()) {
            if (x.getSTime() <= search && x.getETime() >= search) {
                set = x;
                System.out.println("h");
            }
        }

        if (set != null) {
            display.setText("Result Found: " + set.getDescription() + " von " + set.getSTime() + " bis " + set.getETime());
        } else {
            display.setText("No Events found");
        }

    }

    public void delete() {
        //delete previously searched event
        if (set != null) {
            t.l.remove(set);
           display.setText("deleted");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        description = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        end = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        description.setText("Enter Description");
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });

        time.setText("Enter StartTime");

        end.setText("Enter EndTime");

        search.setText("Search for Event by Time");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(end, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(end, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getAttributes();
        fillDisplay();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            suchen(Integer.parseInt(search.getText()));
        } catch (InterruptedException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField description;
    private javax.swing.JTextArea display;
    private javax.swing.JTextField end;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField search;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
